### ISSUE TITLE
Server crash with magma mod bukkit

### ISSUE THREAD

**Issue by IMaFishEatshark** [zabi94/MaxPotionIDExtender#3]
Server crash on startup, works with the client but was wondering if it was unrelated error

[crash-2020-09-26_11.24.24-server.txt](https://github.com/zabi94/MaxPotionIDExtender/files/5286235/crash-2020-09-26_11.24.24-server.txt)

**Comment by zabi94** [comment]
The Bukkit part of the server uses its own registries which still have the old id limit, I suggest you replace plugins with equivalent mods and use a pure forge server.
