### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by Aurocosh** [zabi94/MaxPotionIDExtender#5]
Hello, i am an author of the mod [Divine Favor](https://www.curseforge.com/minecraft/mc-mods/divine-favor). Recently i decided to publish it on modrinth.com. My mod uses yours as an optional dependency, but It seems your mod is not available on Modrinth. My mod adds a lot of modded potion effects and it can be a problem with other mods that add modded potions. Please add your mod to Modrinth.

**Comment by zabi94** [comment]
Sure, I'll do it the first chance I get

**Comment by zabi94** [comment]
It will be available after review at https://modrinth.com/mod/max-potion-id-extender

**Comment by Aurocosh** [comment]
It was quick. Thank you very much!
